#include "tjsCommHead.h"
#include "RenderManager.h"
#include "MetalLayerRenderManager.h"
#include "TVPCompositor.h"
#include "gl/tvpgl.h"
#include <array>
#include <cstring>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
using Texture=std::unique_ptr<iTVPTexture2D>;
constexpr int Width=8, Height=6;
const tTVPRect Whole(0,0,Width,Height);
const tTVPRect ROI(1,1,Width-1,Height-1);

void Require(bool condition,const char* message) {
    if(!condition) throw std::runtime_error(message);
}
std::vector<uint32_t> Pixels(unsigned seed) {
    const unsigned alphas[]={0,1,4,8,16,32,64,128,254,255};
    std::vector<uint32_t> result(Width*Height);
    for(int y=0;y<Height;++y) for(int x=0;x<Width;++x) {
        const unsigned alpha=alphas[(x+y+seed)%10];
        const unsigned low=(x%3==0) ? alpha : (x*37+y*11+seed*17)&255;
        const unsigned middle=(x*19+y*43+seed*53)&255;
        const unsigned high=(x*61+y*7+seed*23)&255;
        result[y*Width+x]=low|(middle<<8)|(high<<16)|(alpha<<24);
    }
    return result;
}
Texture Create(iTVPRenderManager* manager,const std::vector<uint32_t>& pixels) {
    Texture texture(manager->CreateTexture2D(nullptr,0,Width,Height,TVPTextureFormat::RGBA));
    Require(bool(texture),"Gamma test texture allocation failed");
    texture->Update(pixels.data(),TVPTextureFormat::RGBA,Width*4,Whole);
    Require(texture->GetTextureHandle()!=nullptr && !texture->IsCPUResident(),
            "Gamma test input was not GPU resident");
    return texture;
}
void Compare(iTVPTexture2D* texture,const std::vector<uint32_t>& expected,const char* label) {
    for(int y=0;y<Height;++y) {
        const void* row=texture->GetScanLineForRead(y);
        if(!row || std::memcmp(row,expected.data()+y*Width,Width*4)) {
            std::cerr<<label<<" row="<<y<<'\n';
            throw std::runtime_error("Gamma GPU/software exact surface mismatch");
        }
    }
}
TVPLayerOperation Describe(iTVPRenderMethod* method) {
    TVPLayerOperation op;
    Require(method->DescribeGpuOperation(op) && op.kind==TVPLayerOperationKind::AdjustGamma &&
            bool(op.gammaLUT) && op.gammaLUT->bytes.size()==768 && op.gammaLUT->version!=0,
            "Gamma method lost its owned initialized LUT");
    return op;
}
void SoftwareGamma(std::vector<uint32_t>& pixels,const TVPLayerOperation& op,const tTVPRect& roi) {
    static_assert(sizeof(tTVPGLGammaAdjustTempData)==768,"Gamma test/software LUT layout differs");
    tTVPGLGammaAdjustTempData temp;
    std::memcpy(&temp,op.gammaLUT->bytes.data(),sizeof(temp));
    for(int y=roi.top;y<roi.bottom;++y) {
        auto* row=pixels.data()+y*Width+roi.left;
        if(op.flags&TVP_LAYER_DEST_PREMULTIPLIED) TVPAdjustGamma_a(row,roi.get_width(),&temp);
        else TVPAdjustGamma(row,roi.get_width(),&temp);
    }
}
void NoImageTransfer(const TVPLayerRenderStats& before,const TVPLayerRenderStats& after,uint64_t operations) {
    Require(after.gpuOperations==before.gpuOperations+operations && after.cpuFallbacks==before.cpuFallbacks &&
            after.readbackBytes==before.readbackBytes && after.uploadedBytes==before.uploadedBytes,
            "resident Gamma caused image transfer or software fallback");
}
void UploadDelta(const TVPLayerParameterUploadStats& before,const TVPLayerParameterUploadStats& after,
                 uint64_t uploads,const char* message) {
    Require(after.gammaLUTUploads==before.gammaLUTUploads+uploads &&
            after.gammaLUTUploadedBytes==before.gammaLUTUploadedBytes+768*uploads,message);
}

void Variant(krkrsdl3::iTVPRenderBackend* backend,const char* name,bool premultiplied) {
    auto* manager=TVPGetRenderManager();
    auto* method=manager->GetRenderMethod(name);
    Require(method!=nullptr,"Gamma method registration missing");
    const auto initialDescriptor=Describe(method); // Preserve/read the owned default; do not replace it with identity.
    if(initialDescriptor.gammaLUT->version==1)
        for(uint8_t value:initialDescriptor.gammaLUT->bytes)
            Require(value==0,"Gamma default zero LUT was replaced by an identity curve");
    Require(bool(initialDescriptor.flags&TVP_LAYER_DEST_PREMULTIPLIED)==premultiplied,
            "Gamma variant flags changed");
    const int id=method->EnumParameterID("gammaAdjustData");
    Require(id>=0,"Gamma parameter ID missing");
    const tTVPGLGammaAdjustData parametersA={0.73f,5,247,1.41f,19,233,2.27f,31,219};
    const tTVPGLGammaAdjustData parametersB={1.83f,27,227,0.57f,43,211,1.09f,13,239};

    // SetParameterPtr must freeze generated bytes before the user's storage is
    // overwritten and released. It must not retain that short-lived pointer.
    auto shortLived=std::make_unique<tTVPGLGammaAdjustData>(parametersA);
    method->SetParameterPtr(id,shortLived.get());
    const auto operationA=Describe(method);
    const auto bytesA=operationA.gammaLUT->bytes;
    tTVPGLGammaAdjustTempData generatedA;
    TVPInitGammaAdjustTempData(&generatedA,&parametersA);
    Require(!std::memcmp(bytesA.data(),&generatedA,sizeof(generatedA)),"Gamma snapshot differs from software LUT");
    std::memset(shortLived.get(),0xa5,sizeof(*shortLived));
    shortLived.reset();
    Require(Describe(method).gammaLUT==operationA.gammaLUT && operationA.gammaLUT->bytes==bytesA,
            "Gamma retained mutable user parameter storage");

    const auto original=Pixels(2),referencePixels=Pixels(7);
    auto actual=Create(manager,original);
    auto reference=Create(manager,referencePixels);
    auto oldSnapshotTarget=Create(manager,original);
    // Prime sparse alpha/outside caches, then explicitly flush setup work. No
    // read is issued during the small A/A/B/A/old-A pending-buffer burst.
    const auto alpha=actual->GetPointAlpha(2,2);
    const auto outside=actual->GetPoint(0,0);
    Require(alpha==(original[2*Width+2]>>24) && outside==original[0],"Gamma cache priming changed pixels");
    std::vector<uint8_t> setupPixels;
    int setupPitch=0;
    Require(backend->ReadLayerTexture(actual->GetTextureHandle(),setupPixels,setupPitch) &&
            setupPitch>=Width*4 && setupPixels.size()>=size_t(setupPitch)*Height,
            "Gamma setup flush failed");
    const auto baseline=TVPGetMetalLayerRenderStats();
    const auto uploadBaseline=backend->GetLayerParameterUploadStats();
    auto expected=original;

    manager->OperateRect(method,actual.get(),reference.get(),ROI,tRenderTexRectArray());
    SoftwareGamma(expected,operationA,ROI);
    const auto afterA=backend->GetLayerParameterUploadStats();
    Require(afterA.gammaLUTUploads>=uploadBaseline.gammaLUTUploads &&
            afterA.gammaLUTUploads<=uploadBaseline.gammaLUTUploads+1,"first Gamma A uploaded more than once");
    const uint64_t firstUpload=afterA.gammaLUTUploads-uploadBaseline.gammaLUTUploads;
    UploadDelta(uploadBaseline,afterA,firstUpload,"first Gamma A parameter bytes incorrect");
    NoImageTransfer(baseline,TVPGetMetalLayerRenderStats(),1);

    {
        tTVPGLGammaAdjustData temporary=parametersA;
        method->SetParameterPtr(id,&temporary);
        std::memset(&temporary,0x5a,sizeof(temporary));
    }
    const auto operationAA=Describe(method);
    Require(operationAA.gammaLUT==operationA.gammaLUT && operationAA.gammaLUT->version==operationA.gammaLUT->version,
            "same Gamma LUT changed owner/version");
    manager->OperateRect(method,actual.get(),reference.get(),ROI,tRenderTexRectArray());
    SoftwareGamma(expected,operationAA,ROI);
    const auto afterAA=backend->GetLayerParameterUploadStats();
    UploadDelta(afterA,afterAA,0,"same Gamma LUT was uploaded again");

    {
        const tTVPGLGammaAdjustData temporary=parametersB;
        method->SetParameterPtr(id,&temporary);
    }
    const auto operationB=Describe(method);
    Require(operationB.gammaLUT!=operationA.gammaLUT && operationB.gammaLUT->version>operationA.gammaLUT->version &&
            operationA.gammaLUT->bytes==bytesA,"changed Gamma parameter mutated the old snapshot");
    manager->OperateRect(method,actual.get(),reference.get(),ROI,tRenderTexRectArray());
    SoftwareGamma(expected,operationB,ROI);
    const auto afterB=backend->GetLayerParameterUploadStats();
    UploadDelta(afterAA,afterB,1,"Gamma B did not upload one immutable LUT");

    method->SetParameterPtr(id,&parametersA);
    const auto operationAgainA=Describe(method);
    Require(operationAgainA.gammaLUT->version>operationB.gammaLUT->version && operationAgainA.gammaLUT->bytes==bytesA &&
            operationA.gammaLUT->bytes==bytesA,"Gamma A/B/A snapshot history changed");
    // Both distinct-reference and target==reference calls transform old target
    // pixels; Gamma's zero-input contract does not read/copy reference.
    manager->OperateRect(method,actual.get(),actual.get(),ROI,tRenderTexRectArray());
    SoftwareGamma(expected,operationAgainA,ROI);
    const auto afterAgainA=backend->GetLayerParameterUploadStats();
    UploadDelta(afterB,afterAgainA,1,"Gamma restored A did not freeze a new LUT version");
    NoImageTransfer(baseline,TVPGetMetalLayerRenderStats(),4);
    const auto cacheBefore=TVPGetMetalLayerRenderStats();
    Require(actual->GetPointAlpha(2,2)==alpha && actual->GetPoint(0,0)==outside,
            "Gamma changed cached alpha or pixels outside ROI");
    const auto cacheAfter=TVPGetMetalLayerRenderStats();
    Require(cacheAfter.readbackBytes==cacheBefore.readbackBytes && cacheAfter.pointCacheHits>=cacheBefore.pointCacheHits+2,
            "RGB-only Gamma unnecessarily invalidated alpha/outside point caches");
    Require(cacheAfter.gammaLUTUploads-baseline.gammaLUTUploads==afterAgainA.gammaLUTUploads-uploadBaseline.gammaLUTUploads &&
            cacheAfter.gammaLUTUploadedBytes-baseline.gammaLUTUploadedBytes==
                afterAgainA.gammaLUTUploadedBytes-uploadBaseline.gammaLUTUploadedBytes,
            "Gamma session parameter counters disagree with backend counters");

    // A retained operation must still encode its original A LUT after the
    // singleton has advanced through B and a new A revision in this buffer.
    const TVPLayerRect roi{ROI.left,ROI.top,ROI.right,ROI.bottom},unused{};
    void* oldHandle=oldSnapshotTarget->GetTextureHandleForRegionWrite();
    Require(oldHandle && backend->OperateLayerRect(operationA,oldHandle,roi,nullptr,unused,0),
            "retained Gamma snapshot could not encode after parameter replacement");
    oldSnapshotTarget->CommitGPURegionWrite(ROI);
    UploadDelta(afterAgainA,backend->GetLayerParameterUploadStats(),1,
                "retained old Gamma revision was not frozen independently");
    NoImageTransfer(baseline,TVPGetMetalLayerRenderStats(),4);
    auto oldExpected=original;
    SoftwareGamma(oldExpected,operationA,ROI);
    Compare(oldSnapshotTarget.get(),oldExpected,name);
    Compare(actual.get(),expected,name);
    Compare(reference.get(),referencePixels,"Gamma reference must remain unchanged");

    TVPLayerOperation missing=operationAgainA;
    missing.gammaLUT.reset();
    const auto missingBefore=backend->GetLayerParameterUploadStats();
    void* actualHandle=actual->GetTextureHandleForRegionWrite();
    Require(actualHandle && !backend->OperateLayerRect(missing,actualHandle,roi,nullptr,unused,0),
            "Gamma backend accepted a missing LUT");
    UploadDelta(missingBefore,backend->GetLayerParameterUploadStats(),0,"missing Gamma LUT changed parameter upload counters");
    // Force a GPU read so an old CPU mirror cannot hide a write-before-failure.
    actual->InvalidateCPUCache();
    Compare(actual.get(),expected,"missing Gamma LUT changed target pixels");
}
}

void P1AGammaTests(krkrsdl3::iTVPRenderBackend* backend) {
    Require(backend!=nullptr,"Gamma tests need the bound backend");
    Variant(backend,"AdjustGamma",false);
    Variant(backend,"AdjustGamma_a",true);
    std::cout<<"PASS P1A Gamma: target/reference ROI, alpha cache, A/A/B/A snapshots, immutable parameter uploads, missing-LUT rejection\n";
}
