import {chromium} from 'playwright';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('artifacts', {recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,colorScheme:'dark'});
const page=await context.newPage();
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:4173');
  await page.getByRole('heading',{name:'游戏库',exact:true}).waitFor();
  await page.screenshot({path:'artifacts/library.png'});
  await page.getByRole('searchbox',{name:'搜索游戏'}).fill('no-match');
  assert(await page.getByText('没有找到游戏',{exact:true}).isVisible());
  await page.getByRole('button',{name:'清除搜索',exact:true}).click();
  await page.getByRole('button',{name:'列表视图',exact:true}).click();
  assert.equal(await page.locator('.game-grid.list .game-card').count(),1);
  await page.getByRole('button',{name:'网格视图',exact:true}).click();
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await page.getByText('点缀色',{exact:true}).waitFor();
  await page.screenshot({path:'artifacts/settings.png',fullPage:true});
  await page.getByRole('button',{name:'浅色',exact:true}).click();
  assert(await page.locator('body').evaluate(el=>el.classList.contains('light')));
  await page.getByRole('button',{name:'深色',exact:true}).click();
  await page.getByRole('button',{name:'晴蓝',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'设置',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'晴蓝',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'雾灰',exact:true}).click();
  await page.getByRole('switch',{name:'性能分析',exact:true}).click();
  await page.getByRole('button',{name:'游戏库',exact:true}).click();
  await page.getByRole('button',{name:'继续上次：青空下的加缪',exact:true}).click();
  await page.setViewportSize({width:844,height:390});
  await page.getByRole('button',{name:'关闭菜单',exact:true}).waitFor();
  await page.screenshot({path:'artifacts/player-menu.png'});
  await page.getByRole('button',{name:'关闭菜单',exact:true}).click();
  await page.getByRole('button',{name:'唤出游戏菜单',exact:true}).click();
  await page.getByRole('button',{name:'鼠标',exact:true}).click();
  assert(await page.locator('.cursor').isVisible());
  await page.getByRole('button',{name:'退出',exact:true}).click();
  await page.getByRole('button',{name:'返回游戏库',exact:true}).click();
  assert(await page.locator('#player').isHidden());
  assert.deepEqual(errors,[]);
  console.log('PASS: library, search, layouts, theme, settings persistence, landscape menu, mouse state, exit; no page errors.');
} finally { await browser.close(); }
